project_id = "english-variant"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://english-variant.vercel.app"
additional_redirect_urls = ["https://english-variant.vercel.app/**", "http://localhost:3000/**", "englishvariant://auth/callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = true
