/**
 * Starter dataset — 36 hand-picked British vs American contrasts.
 * Scope is intentionally tight for MVP. Each entry is production-quality:
 *   - natural example sentences
 *   - useful clues
 *   - honest confusion traps where they exist
 *
 * Audio URLs are null for MVP; the content schema supports them for later.
 */

import type { ContentItem } from "@english-variant/shared";

export const SEED_CONTENT: ContentItem[] = [
  // ─── Vocabulary ────────────────────────────────────────────────────────────
  {
    id: "lift-elevator",
    category: "vocabulary",
    level: 1,
    tags: ["building", "everyday"],
    uk: {
      term: "lift",
      sentence: "Take the lift to the third floor.",
      audioUrl: null,
    },
    us: {
      term: "elevator",
      sentence: "Take the elevator to the third floor.",
      audioUrl: null,
    },
    clues: ["'Lift' is UK.", "'Elevator' is US."],
    traps: ["In the UK, 'elevator' is understood but sounds American."],
  },
  {
    id: "flat-apartment",
    category: "vocabulary",
    level: 1,
    tags: ["housing", "everyday"],
    uk: {
      term: "flat",
      sentence: "She lives in a one-bedroom flat near the river.",
      audioUrl: null,
    },
    us: {
      term: "apartment",
      sentence: "She lives in a one-bedroom apartment near the river.",
      audioUrl: null,
    },
    clues: ["'Flat' is UK.", "'Apartment' is US."],
    traps: ["In the UK, 'apartment' suggests something larger or more upmarket."],
  },
  {
    id: "queue-line",
    category: "vocabulary",
    level: 1,
    tags: ["everyday"],
    uk: {
      term: "queue",
      sentence: "Join the queue and wait your turn.",
      audioUrl: null,
    },
    us: {
      term: "line",
      sentence: "Get in line and wait your turn.",
      audioUrl: null,
    },
    clues: ["'Queue' is UK.", "'Line' (or 'in line') is US."],
  },
  {
    id: "petrol-gasoline",
    category: "vocabulary",
    level: 2,
    tags: ["transport"],
    uk: {
      term: "petrol",
      sentence: "The car needs more petrol before we reach Bristol.",
      audioUrl: null,
    },
    us: {
      term: "gasoline",
      sentence: "The car needs more gas before we reach Denver.",
      audioUrl: null,
    },
    clues: ["'Petrol' is UK.", "'Gasoline' or 'gas' is US."],
    traps: ["'Gas' in the UK often means natural gas, not fuel."],
  },
  {
    id: "boot-trunk",
    category: "vocabulary",
    level: 2,
    tags: ["transport", "car"],
    uk: {
      term: "boot",
      sentence: "Put the shopping in the boot.",
      audioUrl: null,
    },
    us: {
      term: "trunk",
      sentence: "Put the groceries in the trunk.",
      audioUrl: null,
    },
    clues: ["Rear car storage: 'boot' (UK), 'trunk' (US)."],
  },
  {
    id: "chips-fries",
    category: "vocabulary",
    level: 1,
    tags: ["food"],
    uk: {
      term: "chips",
      sentence: "Fish and chips, please.",
      audioUrl: null,
    },
    us: {
      term: "fries",
      sentence: "Fish and fries, please.",
      audioUrl: null,
    },
    clues: ["UK 'chips' are thick-cut, usually hot.", "US 'fries' are thinner and always hot."],
    traps: ["In the US, 'chips' means crisps.", "In the UK, 'crisps' are cold snacks in a bag."],
  },
  {
    id: "biscuit-cookie",
    category: "vocabulary",
    level: 1,
    tags: ["food"],
    uk: {
      term: "biscuit",
      sentence: "I'll have a biscuit with my tea.",
      audioUrl: null,
    },
    us: {
      term: "cookie",
      sentence: "I'll have a cookie with my coffee.",
      audioUrl: null,
    },
    clues: ["UK 'biscuit' = US 'cookie'."],
    traps: ["A US 'biscuit' is a soft bread roll, not a sweet treat."],
  },
  {
    id: "trousers-pants",
    category: "vocabulary",
    level: 2,
    tags: ["clothing"],
    uk: {
      term: "trousers",
      sentence: "He ironed his trousers for the interview.",
      audioUrl: null,
    },
    us: {
      term: "pants",
      sentence: "He ironed his pants for the interview.",
      audioUrl: null,
    },
    clues: ["'Trousers' is UK.", "'Pants' is US."],
    traps: ["In the UK, 'pants' means underwear — mix this up at your peril."],
  },
  {
    id: "holiday-vacation",
    category: "vocabulary",
    level: 1,
    tags: ["travel"],
    uk: {
      term: "holiday",
      sentence: "We're going on holiday to Spain next month.",
      audioUrl: null,
    },
    us: {
      term: "vacation",
      sentence: "We're going on vacation to Spain next month.",
      audioUrl: null,
    },
    clues: ["'Holiday' is UK.", "'Vacation' is US."],
    traps: ["In the US, 'holiday' specifically means a public holiday."],
  },
  {
    id: "autumn-fall",
    category: "vocabulary",
    level: 1,
    tags: ["seasons"],
    uk: {
      term: "autumn",
      sentence: "The leaves change in autumn.",
      audioUrl: null,
    },
    us: {
      term: "fall",
      sentence: "The leaves change in the fall.",
      audioUrl: null,
    },
    clues: ["'Autumn' is standard in UK.", "'Fall' is more common in US, though 'autumn' is also used."],
  },
  {
    id: "pavement-sidewalk",
    category: "vocabulary",
    level: 1,
    tags: ["city"],
    uk: {
      term: "pavement",
      sentence: "Walk on the pavement, not the road.",
      audioUrl: null,
    },
    us: {
      term: "sidewalk",
      sentence: "Walk on the sidewalk, not the road.",
      audioUrl: null,
    },
    clues: ["'Pavement' is UK.", "'Sidewalk' is US."],
    traps: ["In the US, 'pavement' can mean the road surface itself."],
  },
  {
    id: "underground-subway",
    category: "vocabulary",
    level: 2,
    tags: ["transport", "city"],
    uk: {
      term: "underground",
      sentence: "Take the Underground to King's Cross.",
      audioUrl: null,
    },
    us: {
      term: "subway",
      sentence: "Take the subway to Grand Central.",
      audioUrl: null,
    },
    clues: ["Urban rail: 'Underground'/'Tube' (UK), 'subway' (US)."],
    traps: ["In the UK, a 'subway' is a pedestrian underpass."],
  },

  // ─── Spelling ──────────────────────────────────────────────────────────────
  {
    id: "colour-color",
    category: "spelling",
    level: 1,
    tags: ["suffix-our"],
    uk: {
      term: "colour",
      sentence: "What's your favourite colour?",
      audioUrl: null,
    },
    us: {
      term: "color",
      sentence: "What's your favorite color?",
      audioUrl: null,
    },
    clues: ["UK keeps '-our' in many words (colour, favour, honour).", "US drops the 'u' (color, favor, honor)."],
  },
  {
    id: "centre-center",
    category: "spelling",
    level: 1,
    tags: ["suffix-re"],
    uk: {
      term: "centre",
      sentence: "Meet me at the town centre.",
      audioUrl: null,
    },
    us: {
      term: "center",
      sentence: "Meet me at the town center.",
      audioUrl: null,
    },
    clues: ["UK uses '-re' (centre, theatre, metre).", "US uses '-er' (center, theater, meter)."],
  },
  {
    id: "organise-organize",
    category: "spelling",
    level: 2,
    tags: ["suffix-ise"],
    uk: {
      term: "organise",
      sentence: "Let's organise the files by date.",
      audioUrl: null,
    },
    us: {
      term: "organize",
      sentence: "Let's organize the files by date.",
      audioUrl: null,
    },
    clues: ["Many verbs end in '-ise' (UK) or '-ize' (US): organise, realise, recognise."],
    traps: ["Oxford spelling is UK but uses '-ize'. Most UK publishers prefer '-ise'."],
  },
  {
    id: "analyse-analyze",
    category: "spelling",
    level: 2,
    tags: ["suffix-yse"],
    uk: {
      term: "analyse",
      sentence: "We need to analyse the results before Friday.",
      audioUrl: null,
    },
    us: {
      term: "analyze",
      sentence: "We need to analyze the results before Friday.",
      audioUrl: null,
    },
    clues: ["'-yse' (UK) vs '-yze' (US).", "Also: catalyse/catalyze, paralyse/paralyze."],
  },
  {
    id: "travelled-traveled",
    category: "spelling",
    level: 2,
    tags: ["double-l"],
    uk: {
      term: "travelled",
      sentence: "She travelled across Europe by train.",
      audioUrl: null,
    },
    us: {
      term: "traveled",
      sentence: "She traveled across Europe by train.",
      audioUrl: null,
    },
    clues: ["UK doubles the 'l' before -ed/-ing.", "US keeps a single 'l'."],
    traps: ["Applies to unstressed -el verbs: cancelled/canceled, modelled/modeled."],
  },
  {
    id: "catalogue-catalog",
    category: "spelling",
    level: 2,
    tags: ["suffix-ogue"],
    uk: {
      term: "catalogue",
      sentence: "Order from the autumn catalogue.",
      audioUrl: null,
    },
    us: {
      term: "catalog",
      sentence: "Order from the fall catalog.",
      audioUrl: null,
    },
    clues: ["'-ogue' (UK) vs '-og' (US): catalogue, dialogue, monologue."],
  },
  {
    id: "grey-gray",
    category: "spelling",
    level: 1,
    tags: ["colours"],
    uk: {
      term: "grey",
      sentence: "The sky turned a dull grey.",
      audioUrl: null,
    },
    us: {
      term: "gray",
      sentence: "The sky turned a dull gray.",
      audioUrl: null,
    },
    clues: ["'Grey' is the UK spelling.", "'Gray' is the US spelling."],
  },
  {
    id: "tyre-tire",
    category: "spelling",
    level: 2,
    tags: ["car"],
    uk: {
      term: "tyre",
      sentence: "I need a new tyre before the trip.",
      audioUrl: null,
    },
    us: {
      term: "tire",
      sentence: "I need a new tire before the trip.",
      audioUrl: null,
    },
    clues: ["For the rubber on a wheel: 'tyre' (UK), 'tire' (US)."],
    traps: ["'Tire' meaning 'get tired' is spelt the same in both."],
  },
  {
    id: "cheque-check",
    category: "spelling",
    level: 2,
    tags: ["finance"],
    uk: {
      term: "cheque",
      sentence: "He wrote a cheque for the deposit.",
      audioUrl: null,
    },
    us: {
      term: "check",
      sentence: "He wrote a check for the deposit.",
      audioUrl: null,
    },
    clues: ["Payment slip: 'cheque' (UK), 'check' (US)."],
    traps: ["Only for the financial sense. 'Check the box' is the same in both."],
  },
  {
    id: "aluminium-aluminum",
    category: "spelling",
    level: 3,
    tags: ["science"],
    uk: {
      term: "aluminium",
      sentence: "Wrap it in aluminium foil.",
      audioUrl: null,
    },
    us: {
      term: "aluminum",
      sentence: "Wrap it in aluminum foil.",
      audioUrl: null,
    },
    clues: ["UK: five syllables ('al-yoo-MIN-i-um').", "US: four syllables ('a-LOO-mi-num')."],
  },
  {
    id: "programme-program",
    category: "spelling",
    level: 2,
    tags: ["media"],
    uk: {
      term: "programme",
      sentence: "The programme starts at nine.",
      audioUrl: null,
    },
    us: {
      term: "program",
      sentence: "The program starts at nine.",
      audioUrl: null,
    },
    clues: ["UK uses 'programme' for events/broadcasts; 'program' is kept for software.", "US uses 'program' for everything."],
  },

  // ─── Pronunciation ─────────────────────────────────────────────────────────
  {
    id: "schedule-pronunciation",
    category: "pronunciation",
    level: 2,
    tags: ["common-words"],
    uk: {
      term: "schedule",
      sentence: "Let's stick to the schedule.",
      audioUrl: null,
      ipa: "/ˈʃɛd.juːl/",
    },
    us: {
      term: "schedule",
      sentence: "Let's stick to the schedule.",
      audioUrl: null,
      ipa: "/ˈskɛdʒ.uːl/",
    },
    clues: ["UK starts with a 'sh' sound ('SHED-jool').", "US starts with a 'sk' sound ('SKED-jool')."],
  },
  {
    id: "tomato-pronunciation",
    category: "pronunciation",
    level: 2,
    tags: ["food"],
    uk: {
      term: "tomato",
      sentence: "A fresh tomato, please.",
      audioUrl: null,
      ipa: "/təˈmɑː.təʊ/",
    },
    us: {
      term: "tomato",
      sentence: "A fresh tomato, please.",
      audioUrl: null,
      ipa: "/təˈmeɪ.toʊ/",
    },
    clues: ["UK middle vowel: 'ah' ('to-MAH-to').", "US middle vowel: 'ay' ('to-MAY-to')."],
  },
  {
    id: "privacy-pronunciation",
    category: "pronunciation",
    level: 3,
    tags: ["common-words"],
    uk: {
      term: "privacy",
      sentence: "I value my privacy.",
      audioUrl: null,
      ipa: "/ˈprɪv.ə.si/",
    },
    us: {
      term: "privacy",
      sentence: "I value my privacy.",
      audioUrl: null,
      ipa: "/ˈpraɪ.və.si/",
    },
    clues: ["UK starts with 'PRI' (short 'i').", "US starts with 'PRY' (long 'i')."],
  },
  {
    id: "rhotic-r",
    category: "pronunciation",
    level: 3,
    tags: ["accent"],
    uk: {
      term: "car",
      sentence: "The car is outside.",
      audioUrl: null,
      ipa: "/kɑː/",
    },
    us: {
      term: "car",
      sentence: "The car is outside.",
      audioUrl: null,
      ipa: "/kɑːr/",
    },
    clues: ["Standard UK English is non-rhotic — the 'r' at the end is dropped.", "Standard US English is rhotic — the 'r' is pronounced."],
    traps: ["West-Country UK accents are rhotic too. New England US accents drop their r's."],
  },

  // ─── Grammar ───────────────────────────────────────────────────────────────
  {
    id: "at-the-weekend",
    category: "grammar",
    level: 2,
    tags: ["prepositions"],
    uk: {
      term: "at the weekend",
      sentence: "I'll see you at the weekend.",
      audioUrl: null,
    },
    us: {
      term: "on the weekend",
      sentence: "I'll see you on the weekend.",
      audioUrl: null,
    },
    clues: ["UK uses 'at the weekend'.", "US uses 'on the weekend'."],
  },
  {
    id: "in-hospital",
    category: "grammar",
    level: 2,
    tags: ["articles"],
    uk: {
      term: "in hospital",
      sentence: "She's been in hospital since Tuesday.",
      audioUrl: null,
    },
    us: {
      term: "in the hospital",
      sentence: "She's been in the hospital since Tuesday.",
      audioUrl: null,
    },
    clues: ["UK drops 'the' before institutions (in hospital, at university).", "US keeps it (in the hospital, in college)."],
  },
  {
    id: "have-got",
    category: "grammar",
    level: 2,
    tags: ["verbs"],
    uk: {
      term: "have got",
      sentence: "I've got a meeting at three.",
      audioUrl: null,
    },
    us: {
      term: "have",
      sentence: "I have a meeting at three.",
      audioUrl: null,
    },
    clues: ["UK: 'have got' is natural in present-day usage.", "US: simple 'have' is more common."],
    traps: ["Both exist in both dialects; this is a frequency difference, not a right/wrong one."],
  },
  {
    id: "past-tense-learnt",
    category: "grammar",
    level: 2,
    tags: ["verbs", "past-tense"],
    uk: {
      term: "learnt",
      sentence: "She learnt French in school.",
      audioUrl: null,
    },
    us: {
      term: "learned",
      sentence: "She learned French in school.",
      audioUrl: null,
    },
    clues: ["UK allows both 'learnt' and 'learned' in the past tense.", "US prefers 'learned'."],
    traps: ["Same pattern for: burnt/burned, dreamt/dreamed, spelt/spelled."],
  },
  {
    id: "collective-plural",
    category: "grammar",
    level: 3,
    tags: ["agreement"],
    uk: {
      term: "the team are",
      sentence: "The team are playing well.",
      audioUrl: null,
    },
    us: {
      term: "the team is",
      sentence: "The team is playing well.",
      audioUrl: null,
    },
    clues: ["UK often treats collective nouns as plural (the team are).", "US treats them as singular (the team is)."],
  },
  {
    id: "past-participle-gotten",
    category: "grammar",
    level: 2,
    tags: ["verbs"],
    uk: {
      term: "have got",
      sentence: "The weather has got worse.",
      audioUrl: null,
    },
    us: {
      term: "have gotten",
      sentence: "The weather has gotten worse.",
      audioUrl: null,
    },
    clues: ["UK: past participle is 'got'.", "US: past participle is often 'gotten', especially for 'become'/'obtain' senses."],
  },

  // ─── Usage ─────────────────────────────────────────────────────────────────
  {
    id: "at-university",
    category: "usage",
    level: 2,
    tags: ["education"],
    uk: {
      term: "at university",
      sentence: "She's at university in Edinburgh.",
      audioUrl: null,
    },
    us: {
      term: "in college",
      sentence: "She's in college in Boston.",
      audioUrl: null,
    },
    clues: ["UK 'at university' covers the whole institution.", "US 'in college' typically covers undergraduate study."],
    traps: ["In the US, 'university' exists too but 'college' is the default conversational term."],
  },
  {
    id: "first-floor",
    category: "usage",
    level: 2,
    tags: ["building"],
    uk: {
      term: "first floor",
      sentence: "Her office is on the first floor — one up from the entrance.",
      audioUrl: null,
    },
    us: {
      term: "second floor",
      sentence: "Her office is on the second floor — one up from the entrance.",
      audioUrl: null,
    },
    clues: ["UK ground floor = US first floor.", "UK first floor = US second floor."],
    traps: ["This is a counting difference, not a word difference. Always confirm the floor by function."],
  },
  {
    id: "dates-format",
    category: "usage",
    level: 1,
    tags: ["dates"],
    uk: {
      term: "5 November 2025",
      sentence: "The event is on 5 November 2025.",
      audioUrl: null,
    },
    us: {
      term: "November 5, 2025",
      sentence: "The event is on November 5, 2025.",
      audioUrl: null,
    },
    clues: ["UK: day-month-year.", "US: month-day-year."],
  },
  {
    id: "time-format",
    category: "usage",
    level: 2,
    tags: ["time"],
    uk: {
      term: "half seven",
      sentence: "Shall we meet at half seven?",
      audioUrl: null,
    },
    us: {
      term: "seven-thirty",
      sentence: "Shall we meet at seven-thirty?",
      audioUrl: null,
    },
    clues: ["UK speakers often say 'half seven' meaning 7:30.", "US speakers say 'seven-thirty' or 'half past seven'."],
    traps: ["German uses 'half seven' to mean 6:30 — don't confuse the two."],
  },
];
